version: '3.8'
services:
  # MONGO #
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  # REDIS #
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # APPS #
  app:
    image: 25ktest:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MODE=events
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URI=redis://redis:6379
  
  # calculate:
  #   image: 25ktest:latest
  #   ports:
  #     - "3009:3009"
  #   environment:
  #     - NODE_ENV=production
  #     - MODE=worker
  #     - MONGO_URI=mongodb://mongo:27017
  #     - KAFKA_BROKERS=["redpanda-0:9092"]
  #     - REDIS_URI=redis://redis:6379
  #   depends_on:
  #     - redpanda-0

volumes:
  mongodb_data:
  redpanda-0: