version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.10
    container_name: redpanda-0
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.7.2
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-0:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-0:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda-0

  app:
    image: 25ktest:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redpanda-0
  app2:
    image: 25ktest:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - redpanda-0
  app3:
    image: 25ktest:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    depends_on:
      - redpanda-0
  app4:
    image: 25ktest:latest
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    depends_on:
      - redpanda-0
  app5:
    image: 25ktest:latest
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
    depends_on:
      - redpanda-0
  app6:
    image: 25ktest:latest
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
    depends_on:
      - redpanda-0
  app7:
    image: 25ktest:latest
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
    depends_on:
      - redpanda-0
  app8:
    image: 25ktest:latest
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
    depends_on:
      - redpanda-0
  app9:
    image: 25ktest:latest
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
    depends_on:
      - redpanda-0
  app10:
    image: 25ktest:latest
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
    depends_on:
      - redpanda-0

volumes:
  mongodb_data:
  redpanda-0: